openapi: 3.1.0
info:
  version: 1.0.0
  title: Crisis connect API
  contact:
    email: contact@crisisconnect.com
tags:
  - name: Authentication
    description: Operations about the authentication
  - name: Events
    description: Operations about events
servers:
  - url: https://api.abiehler.com/
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a user
      description: |
        This route is for create an account.
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: email of the user
                  type: string
                  required: true
                  example: contact@crisisconnect.com
                username:
                  description: user name
                  type: string
                  required: true
                  example: crisis
                password:
                  description: Password of the user account
                  type: string
                  required: true
                  example: sample password
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                status: true
                body: User created
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login a user
      description: |
        This route is to login an account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: email of the user
                  type: string
                  example: contact@crisisconnect.com
                password:
                  description: Password of the user account
                  type: string
                  minLength: 1
                  example: sample password
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                status: true
                body:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF4ZWwiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzk3Njk2MDYsImV4cCI6MTY3OTg1NjAwNiwic3ViIjoiMiJ9.vszzJd6wNmCBttxPmX6Ow1pEuqlBTMgP3IGpIiGQrto
  /event/all:
    get:
      tags:
        - Events
      summary: Get all events
      operationId: getEvents
      description: |
        Get all events with filter if needed.
      parameters:
        - name: search
          in: path
          description: The search string that search on name field
          schema:
            type: string
        - name: type
          in: path
          description: type of event to query separated by ','
          schema:
            type: string
          example: WeatherEvent,CovidEvent,SecurityEvent,WildfireEvent
        - name: location
          in: path
          description: location of the event
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  body:
                    type: object
                    properties:
                      CovidEvent:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              format: int32
                              example: 1
                            covid_cases:
                              type: integer
                              format: int32
                              example: 15000
                            covid_death:
                              type: integer
                              format: int32
                              example: 12
                            data:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:31:08.000Z'
                            name:
                              type: string
                              example: covid increase
                            county_name:
                              type: string
                              example: SF
                            createdAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:31:16.000Z'
                            updatedAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:31:17.000Z'
                      WeatherEvent:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              format: int32
                              example: 1
                            temperature:
                              type: integer
                              format: int32
                              example: 15
                            wind_speed:
                              type: integer
                              format: int32
                              example: 100
                            precipitation:
                              type: integer
                              format: int32
                              example: 12
                            uv_index:
                              type: integer
                              format: int32
                              example: 6
                            name:
                              type: string
                              example: Wind
                            county_name:
                              type: string
                              example: SF
                            createdAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:31:53.000Z'
                            updatedAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:31:56.000Z'
                      SecurityEvent:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              format: int32
                              example: 1
                            reported_incident:
                              type: string
                              example: vol a main armer
                            date:
                              type: string
                              format: date-time
                              example: '2023-03-25T01:14:42.000Z'
                            name:
                              type: string
                              example: vol 2
                            county_name:
                              type: string
                              example: San Francisco
                            createdAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T01:14:44.000Z'
                            updatedAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T01:14:46.000Z'
                      WildfireEvent:
                        type: array
                        items:
                          type: object
                          properties:
                            user_id:
                              type: integer
                              format: int32
                              example: 1
                            evac_level:
                              type: integer
                              format: int32
                              example: 2
                            wildfire_count:
                              type: integer
                              format: int32
                              example: 10
                            name:
                              type: string
                              example: Wildfire
                            county_name:
                              type: string
                              example: SF
                            createdAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:32:13.000Z'
                            updatedAt:
                              type: string
                              format: date-time
                              example: '2023-03-25T12:32:14.000Z'
components: {}
